#!/usr/bin/env bash
# Deploy cloudflared tunnel to Pi k3s.
# Requires: sealed-secret.yaml already generated by seal.sh
set -euo pipefail

export KUBECONFIG="$HOME/.kube/kubepi"

DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -s "$DIR/sealed-secret.yaml" ] || grep -q "^#" "$DIR/sealed-secret.yaml" && [ "$(wc -l < "$DIR/sealed-secret.yaml")" -le 2 ]; then
  echo "Error: sealed-secret.yaml is empty. Run seal.sh first."
  exit 1
fi

kubectl apply -f "$DIR/cloudflared.yaml"
kubectl apply -f "$DIR/sealed-secret.yaml"
kubectl rollout status deployment/cloudflared -n cloudflared --timeout=120s
