---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCIUge2nsPSC8MP/3iNZq9BcfXWZSCluJr1740SsDzP7C+fGLezlPqScnregX6ntfcGyK9eoHK38LPOkEcCp4DhuPWwylmeHPsgL55cv+ijiVQq17kNX2ozr0vhS1nN7bIk3pnydgMmmWonLWSkLidEUTQDPgiWlTlfc4L8p4iyLPvHAgCD4+UwBCupx7EcnDwzFJiS89u2nvdSc6RucUDlSiMfkefUuGxQhN7K11B9H4GYQX1gBXaX7qYt+7LuifugLlCH97rfjePlJT2eEW0s7aluLwFBYfqAQkAcMTfZNEOnzSVqlNiXilYr59pLgxnEWRx2oWQtgMif2HxE3xWZKMABokQ8VrY47ECbG4Z8bH5NzOEdNcS5Xx60tyoolT99QipJJwJX4wDn1vR8NIDS5B7+HuqM9orZJEaWaf45qF09jLiUcSJomP7D+tR7XqvXqb+slN/n556sVsrlQsFWqPCzV9OGD7oYECoQIW54QyePXcAzqoxuIXnkSGMY+14tf2KRMXZ0UhQJUYqFr1A4GlgsRjbyKUiiHMAgIK0dnRBPSD371eGgVNrA1z6arbUaHIb3Yf5tefoL4PRQRKH4Y3bXe6wD23YnSJDVDQ4hPHR5LNt82LXQ4T4kMjrHD4rz6XpSLgcGnfVOFf9kXw+FmH4pd86LplkG9XW+xTUH89ZtJJLBRyh9+CC7wR82Yc09nG4ZsGoo0Fc0qPvM4+amD9XYOZYqDIhoeaGZhzhC714I8AOPJrxtHGuyq72l/jecvkU/ZdThYCTuBytcjWz3Q5CCsYe+kw0XW+zcJshpET1gu0Dlz4sBVbvw9VES+wCRqpe5H3yZDyH6j3XC9pO4tSNQLkL53X/mJYz2rb+goIE7Cjh2WY6nAN69ymWM9lozt6pLU1wMyols62DaM2LJi5XtbJp3pFf8T5f0ehIIWZjoE/w=
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
